version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 533567531172.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image with no cache...
      - docker build --no-cache -t wisr-frontend .
      - docker tag wisr-frontend:latest 533567531172.dkr.ecr.ca-central-1.amazonaws.com/wisr-frontend:latest
      - docker tag wisr-frontend:latest 533567531172.dkr.ecr.ca-central-1.amazonaws.com/wisr-frontend:v12-chat-docs-fix
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 533567531172.dkr.ecr.ca-central-1.amazonaws.com/wisr-frontend:latest
      - docker push 533567531172.dkr.ecr.ca-central-1.amazonaws.com/wisr-frontend:v12-chat-docs-fix
      - echo Build completed on `date`
